export const NAVIGATION_ROUTE_NAMES = {
  HOME: 'HOME',
  DEBIT_CARD: 'DEBIT_CARD',
  PAYMENTS: 'PAYMENTS',
  CREDIT: 'CREDIT',
  PROFILE: 'PROFILE',
  DEBIT_CARD_STACK: {
    DEBIT_CARD_LANDING_SCREEN: 'DEBIT_CARD_LANDING_SCREEN',
    ADD_SPENDING_LIMIT: 'ADD_SPENDING_LIMIT',
  },
};
